_prefs:
  mapid: ''
  saveCenter: false
_properties:
  transport:
    "group-by": layer
scale: 1
metatile: 1
interactivity_layer: ''
name: Brighmed
description: OSM for Wikipedia with Meddo tiles
bounds: &world
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
center:
  - 0
  - 0
  - 4
format: "png"
minzoom: 0
maxzoom: 19
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
source: "tmsource:///home/user/path/to/meddo"
styles:
  - style.mss
  - water.mss
  - land.mss
  - building.mss
  - transport-vars.mss
  - transport.mss
  - air.mss
  - transit.mss
  - admin.mss
  - place.mss
layers:
  - landcover
  - landuse
  - waterway
  - water
  - pier
  - building
  - transport
  - aeroway
  - park
  - boundary
  - country_name
  - place
  - state_name
  - transport_name
  - landcover_name
  - transit_stop
